/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SearchEngineController;
//import org.jfree.chart.axis.NumberAxis; 
import org.jfree.chart.*;

import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.*;
import org.jfree.data.xy.*;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import org.jfree.data.general.DefaultPieDataset;
/*import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
*/



/**
 *
 * @author luigi
 */
public class StatisticsView extends javax.swing.JFrame {

    /**
     * Creates new form StatisticsView
     */
    public StatisticsView(SearchEngineController searchEngine) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLineGraphPane.setVisible(false);
        this.jBarGraphicPane.setVisible(false);
        this.jPieChartPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPane = new javax.swing.JLayeredPane();
        jLineGraphPane = new javax.swing.JPanel();
        jBarGraphicPane = new javax.swing.JPanel();
        jPieChartPane = new javax.swing.JPanel();
        jLineGraphRadioBtn = new javax.swing.JRadioButton();
        jBarGraphicRadioBtn = new javax.swing.JRadioButton();
        jPieChartRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jMainPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jLineGraphPaneLayout = new javax.swing.GroupLayout(jLineGraphPane);
        jLineGraphPane.setLayout(jLineGraphPaneLayout);
        jLineGraphPaneLayout.setHorizontalGroup(
            jLineGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jLineGraphPaneLayout.setVerticalGroup(
            jLineGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jBarGraphicPaneLayout = new javax.swing.GroupLayout(jBarGraphicPane);
        jBarGraphicPane.setLayout(jBarGraphicPaneLayout);
        jBarGraphicPaneLayout.setHorizontalGroup(
            jBarGraphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        jBarGraphicPaneLayout.setVerticalGroup(
            jBarGraphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPieChartPaneLayout = new javax.swing.GroupLayout(jPieChartPane);
        jPieChartPane.setLayout(jPieChartPaneLayout);
        jPieChartPaneLayout.setHorizontalGroup(
            jPieChartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );
        jPieChartPaneLayout.setVerticalGroup(
            jPieChartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMainPaneLayout = new javax.swing.GroupLayout(jMainPane);
        jMainPane.setLayout(jMainPaneLayout);
        jMainPaneLayout.setHorizontalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLineGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jBarGraphicPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPieChartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jMainPaneLayout.setVerticalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLineGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jBarGraphicPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPieChartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jMainPane.setLayer(jLineGraphPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jMainPane.setLayer(jBarGraphicPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jMainPane.setLayer(jPieChartPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLineGraphRadioBtn.setText("Lineas");
        jLineGraphRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLineGraphRadioBtnActionPerformed(evt);
            }
        });

        jBarGraphicRadioBtn.setText("Barras");
        jBarGraphicRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarGraphicRadioBtnActionPerformed(evt);
            }
        });

        jPieChartRadioBtn.setText("Pastel");
        jPieChartRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPieChartRadioBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLineGraphRadioBtn)
                    .addComponent(jBarGraphicRadioBtn)
                    .addComponent(jPieChartRadioBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jMainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLineGraphRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBarGraphicRadioBtn)
                .addGap(12, 12, 12)
                .addComponent(jPieChartRadioBtn)
                .addContainerGap(243, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLineGraphRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLineGraphRadioBtnActionPerformed
        jLineGraphPane.setVisible(true);
        jMainPane.setLayer(jLineGraphPane, 0, 0);
        jBarGraphicPane.setVisible(false);
        jPieChartPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jLineGraphRadioBtnActionPerformed

    private void jBarGraphicRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarGraphicRadioBtnActionPerformed
        jBarGraphicPane.setVisible(true);
        jMainPane.setLayer(jBarGraphicPane, 0, 0);
        jLineGraphPane.setVisible(false);
        jPieChartPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jBarGraphicRadioBtnActionPerformed

    private void jPieChartRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPieChartRadioBtnActionPerformed
        jPieChartPane.setVisible(true);
        jMainPane.setLayer(jPieChartPane, 0, 0);
        jLineGraphPane.setVisible(false);
        jBarGraphicPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jPieChartRadioBtnActionPerformed

    private void loadGraphic(){
        ChartPanel panel;
        JFreeChart chart = null;
        if(jLineGraphRadioBtn.isSelected()){
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            
            XYSeries serie = new XYSeries("Data");
            XYPlot plot;
            
            jLineGraphPane.removeAll();
            
            try{
                serie.add(Float.parseFloat(String.valueOf("1")), Float.parseFloat(String.valueOf("1")));
                serie.add(Float.parseFloat(String.valueOf("2")), Float.parseFloat(String.valueOf("3")));
                serie.add(Float.parseFloat(String.valueOf("3")), Float.parseFloat(String.valueOf("7")));
                serie.add(Float.parseFloat(String.valueOf("4")), Float.parseFloat(String.valueOf("7")));
                serie.add(Float.parseFloat(String.valueOf("5")), Float.parseFloat(String.valueOf("6")));
            }
            catch(Exception ex){
                System.err.println("ERROR: " + ex.getMessage());
            }
            dataset.addSeries(serie);
            
            x.setLabel("Eje x");
            y.setLabel("Eje y");
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
            chart.setTitle("Line graph");
            
        }
        else if(jBarGraphicRadioBtn.isSelected()){
            DefaultCategoryDataset data = new DefaultCategoryDataset();
            String producto1 = "sopas";
            String producto2 = "sopas";
            
            String dia1 = "Dia 1";
            String dia2 = "Dia 2";
            String dia3 = "Dia 3";
            String dia4 = "Dia 4";
            
            data.addValue(18, producto1, dia1);
            data.addValue(15, producto1, dia2);
            data.addValue(14, producto1, dia3);
            data.addValue(1, producto1, dia4);
            
            data.addValue(50, producto2, dia1);
            data.addValue(45, producto2, dia2);
            data.addValue(31, producto2, dia3);
            data.addValue(10, producto2, dia4);
            
            chart = ChartFactory.createBarChart("Grafico de barras", 
                    "Dia",
                    "Cantidad", 
                    data, 
                    PlotOrientation.HORIZONTAL, 
                    true, 
                    true, 
                    true
            );
            
            CategoryPlot plot = (CategoryPlot) chart.getCategoryPlot();
            plot.setDomainGridlinesVisible(true);
        }
        else if(jPieChartRadioBtn.isSelected()){
            DefaultPieDataset data = new DefaultPieDataset();
            data.setValue("Categoria 1", 20);
            data.setValue("Categoria 2", 60);
            data.setValue("Categoria 3", 22);
            
            chart = ChartFactory.createPieChart3D("Pie Graphic", data, true, true, true);            
        }
        panel = new ChartPanel(chart);
        panel.setBounds(5, 10, 410, 350);    
        rePaint(panel);
    }
    
    private void rePaint(ChartPanel panel){
        if(jLineGraphRadioBtn.isSelected()){
            jLineGraphPane.add(panel);
            jLineGraphPane.repaint();
        }
        else if(jBarGraphicRadioBtn.isSelected()){
            jBarGraphicPane.add(panel);
            jBarGraphicPane.repaint();
        }
        else if(jPieChartRadioBtn.isSelected()){
            jPieChartPane.add(panel);
            jPieChartPane.repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBarGraphicPane;
    private javax.swing.JRadioButton jBarGraphicRadioBtn;
    private javax.swing.JPanel jLineGraphPane;
    private javax.swing.JRadioButton jLineGraphRadioBtn;
    private javax.swing.JLayeredPane jMainPane;
    private javax.swing.JPanel jPieChartPane;
    private javax.swing.JRadioButton jPieChartRadioBtn;
    // End of variables declaration//GEN-END:variables
}
