/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.SearchEngineController;
import java.util.ArrayList;
import models.Token;
import views.SearchEngineView;
//import org.jfree.chart.axis.NumberAxis; 
import org.jfree.chart.*;

import org.jfree.chart.renderer.xy.XYSplineRenderer;
import org.jfree.chart.plot.XYPlot;
import org.jfree.chart.axis.*;
import org.jfree.data.xy.*;

import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import org.jfree.data.general.DefaultPieDataset;
/*import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
*/



/**
 *
 * @author luigi
 */
public class StatisticsView extends javax.swing.JFrame {

    
    /**
     * Creates new form StatisticsView
     */
    public StatisticsView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jLineGraphPane.setVisible(false);
        this.jBarGraphicPane.setVisible(false);
        this.jPieChartPane.setVisible(false);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMainPane = new javax.swing.JLayeredPane();
        jLineGraphPane = new javax.swing.JPanel();
        jBarGraphicPane = new javax.swing.JPanel();
        jPieChartPane = new javax.swing.JPanel();
        jMatchesSequentialGraphRadioBtn = new javax.swing.JRadioButton();
        jTimeSequentialGraphicRadioBtn = new javax.swing.JRadioButton();
        jMatchesParallelRadioBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jMainPane.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jLineGraphPaneLayout = new javax.swing.GroupLayout(jLineGraphPane);
        jLineGraphPane.setLayout(jLineGraphPaneLayout);
        jLineGraphPaneLayout.setHorizontalGroup(
            jLineGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        jLineGraphPaneLayout.setVerticalGroup(
            jLineGraphPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jBarGraphicPaneLayout = new javax.swing.GroupLayout(jBarGraphicPane);
        jBarGraphicPane.setLayout(jBarGraphicPaneLayout);
        jBarGraphicPaneLayout.setHorizontalGroup(
            jBarGraphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jBarGraphicPaneLayout.setVerticalGroup(
            jBarGraphicPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 362, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPieChartPaneLayout = new javax.swing.GroupLayout(jPieChartPane);
        jPieChartPane.setLayout(jPieChartPaneLayout);
        jPieChartPaneLayout.setHorizontalGroup(
            jPieChartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );
        jPieChartPaneLayout.setVerticalGroup(
            jPieChartPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 336, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jMainPaneLayout = new javax.swing.GroupLayout(jMainPane);
        jMainPane.setLayout(jMainPaneLayout);
        jMainPaneLayout.setHorizontalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLineGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jBarGraphicPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPieChartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jMainPaneLayout.setVerticalGroup(
            jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jMainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLineGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jMainPaneLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jBarGraphicPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jMainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jMainPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPieChartPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jMainPane.setLayer(jLineGraphPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jMainPane.setLayer(jBarGraphicPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jMainPane.setLayer(jPieChartPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMatchesSequentialGraphRadioBtn.setText("Coincidencia");
        jMatchesSequentialGraphRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatchesSequentialGraphRadioBtnActionPerformed(evt);
            }
        });

        jTimeSequentialGraphicRadioBtn.setText("Tiempo total por sitio");
        jTimeSequentialGraphicRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTimeSequentialGraphicRadioBtnActionPerformed(evt);
            }
        });

        jMatchesParallelRadioBtn.setText("Coincidencias");
        jMatchesParallelRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMatchesParallelRadioBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Graficos Secuenciales");

        jLabel2.setText("Graficos Multinucleo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMatchesSequentialGraphRadioBtn)
                    .addComponent(jTimeSequentialGraphicRadioBtn)
                    .addComponent(jMatchesParallelRadioBtn)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jMainPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMainPane)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMatchesSequentialGraphRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTimeSequentialGraphicRadioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMatchesParallelRadioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMatchesSequentialGraphRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatchesSequentialGraphRadioBtnActionPerformed
        jLineGraphPane.setVisible(true);
        jMainPane.setLayer(jLineGraphPane, 0, 0);
        jBarGraphicPane.setVisible(false);
        jPieChartPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jMatchesSequentialGraphRadioBtnActionPerformed

    private void jTimeSequentialGraphicRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTimeSequentialGraphicRadioBtnActionPerformed
        jBarGraphicPane.setVisible(true);
        jMainPane.setLayer(jBarGraphicPane, 0, 0);
        jLineGraphPane.setVisible(false);
        jPieChartPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jTimeSequentialGraphicRadioBtnActionPerformed

    private void jMatchesParallelRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMatchesParallelRadioBtnActionPerformed
        jPieChartPane.setVisible(true);
        jMainPane.setLayer(jPieChartPane, 0, 0);
        jLineGraphPane.setVisible(false);
        jBarGraphicPane.setVisible(false);
        loadGraphic();
    }//GEN-LAST:event_jMatchesParallelRadioBtnActionPerformed

    private void loadGraphic(){
        ChartPanel panel;
        JFreeChart chart = null;
        if(jMatchesSequentialGraphRadioBtn.isSelected()){
            XYSplineRenderer renderer = new XYSplineRenderer();
            XYSeriesCollection dataset = new XYSeriesCollection();
            
            ValueAxis x = new NumberAxis();
            ValueAxis y = new NumberAxis();
            
            XYSeries serie = new XYSeries("Data");
            XYPlot plot;
            
            jLineGraphPane.removeAll();
            
            try{
                serie.add(Float.parseFloat(String.valueOf("1")), Float.parseFloat(String.valueOf("1")));
                serie.add(Float.parseFloat(String.valueOf("2")), Float.parseFloat(String.valueOf("3")));
                serie.add(Float.parseFloat(String.valueOf("3")), Float.parseFloat(String.valueOf("7")));
                serie.add(Float.parseFloat(String.valueOf("4")), Float.parseFloat(String.valueOf("7")));
                serie.add(Float.parseFloat(String.valueOf("5")), Float.parseFloat(String.valueOf("6")));
            }
            catch(Exception ex){
                System.err.println("ERROR: " + ex.getMessage());
            }
            dataset.addSeries(serie);
            
            x.setLabel("Eje x");
            y.setLabel("Eje y");
            plot = new XYPlot(dataset, x, y, renderer);
            chart = new JFreeChart(plot);
            chart.setTitle("Line graph");
            
        }
        else if(jTimeSequentialGraphicRadioBtn.isSelected()){
            DefaultCategoryDataset data = new DefaultCategoryDataset();
            for(int i=0;i<SearchEngineView.listSitesSequential.size();i++){
                
                //data.addValue(totalmilis, palabra, sitio);
                ArrayList<Token> listTokenMatch= SearchEngineView.listSitesSequential.get(i).getListTokensMatches();
                for(int i2=0;i2<listTokenMatch.size();i2++){
                    data.addValue(listTokenMatch.get(i2).getTotalMachTime(), listTokenMatch.get(i2).getToken(), SearchEngineView.listSitesSequential.get(i).getTitle());
                }
            }
            chart = ChartFactory.createBarChart("Tiempo Total por PaginaWeb", 
                    "Paginas",
                    "Tiempo en milisegundos", 
                    data, 
                    PlotOrientation.HORIZONTAL, 
                    true, 
                    true, 
                    true
            );
            
            CategoryPlot plot = (CategoryPlot) chart.getCategoryPlot();
            plot.setDomainGridlinesVisible(true);
        }
        else if(jMatchesParallelRadioBtn.isSelected()){
            DefaultPieDataset data = new DefaultPieDataset();
            data.setValue("Categoria 1", 20);
            data.setValue("Categoria 2", 60);
            data.setValue("Categoria 3", 22);
            
            chart = ChartFactory.createPieChart3D("Pie Graphic", data, true, true, true);            
        }
        panel = new ChartPanel(chart);
        panel.setBounds(5, 10, 410, 350);    
        rePaint(panel);
    }
    
    private void rePaint(ChartPanel panel){
        if(jMatchesSequentialGraphRadioBtn.isSelected()){
            jLineGraphPane.add(panel);
            jLineGraphPane.repaint();
        }
        else if(jTimeSequentialGraphicRadioBtn.isSelected()){
            jBarGraphicPane.add(panel);
            jBarGraphicPane.repaint();
        }
        else if(jMatchesParallelRadioBtn.isSelected()){
            jPieChartPane.add(panel);
            jPieChartPane.repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatisticsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBarGraphicPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jLineGraphPane;
    private javax.swing.JLayeredPane jMainPane;
    private javax.swing.JRadioButton jMatchesParallelRadioBtn;
    private javax.swing.JRadioButton jMatchesSequentialGraphRadioBtn;
    private javax.swing.JPanel jPieChartPane;
    private javax.swing.JRadioButton jTimeSequentialGraphicRadioBtn;
    // End of variables declaration//GEN-END:variables
}
